version: '3.1'
services:
  db:
    image: postgres
    networks:
      - appnetwork
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    image: adminer
    networks:
      - appnetwork
    restart: always
    ports:
      - 8088:8080
  backend:
    build: ./backend
    networks:
      - appnetwork
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file: 'backend/.env'
networks:
  appnetwork:
